### ISSUE TITLE
Error when an Identifier is being broken up by buffer ending

### ISSUE THREAD

**Issue by whc2001** [CXuesong/Luaon.NET#3]
I believe this is actually a continuation of #1, but since it's closed and I don't seem to have a way to reopen it, I'll open up a new issue.

Seems like there is still some problem with the buffering mechanism. When there is an identifier being broken up by buffer ending, it would be read as two separate identifiers causing error.

![image](https://user-images.githubusercontent.com/16266909/150666720-73740d0a-82d4-4fd7-8956-4700111eab94.png)

![image](https://user-images.githubusercontent.com/16266909/150666724-be29e74a-1fd0-41a2-a739-d45f9f0a4c86.png)

![image](https://user-images.githubusercontent.com/16266909/150666737-95a7e90e-0034-49bb-b750-07283174bc3d.png)

After investigating seems like I missed something the last time. If I comprehend correctly, `EnsureBuffer(len)` should return `true` when there is actually `len` chars to read (those many of chars can be ensured, like the method name), and `false` if no further chars are available. However at line 242: 

https://github.com/CXuesong/Luaon.NET/blob/146db4e240df8505e17ae0d69a3b3e91e46a75d4/Luaon.NET/LuaTableTextReader.cs#L235-L243

After the `if` on line 237, a successful state can be assured (there is more char to read). So looks like it should return `true` instead. I tested locally with the file that I need to parse and seems like it's working.

**Comment by CXuesong** [comment]
Nice catch! Fixed and released [`v0.2.4`](https://github.com/CXuesong/Luaon.NET/releases/tag/v0.2.4).
